name: urbantech
description: "Industry Tech"

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  marvelous_carousel: ^0.0.16
  lottie: ^3.1.3
  multi_dropdown: ^3.0.1
  simple_tags: ^0.0.6
  animations: ^2.0.11
  persistent_bottom_nav_bar: ^6.2.1
  get: ^4.6.6
  intl_phone_number_input: ^0.7.4
  select_field: ^2.0.0
  animated_rating_stars: ^1.0.1
  chat_bubbles: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true

  assets:
    - lib/assets/
